"""IATA → (city, country). Names only — the timetable needs no coordinates."""

AIRPORTS = {
    "ABV": ("Абуджа", "Nigeria"),
    "ACC": ("Аккра", "Ghana"),
    "ADD": ("Аддис-Абеба", "Ethiopia"),
    "ADE": ("Аден", "Yemen"),
    "ALA": ("Алматы", "Kazakhstan"),
    "ALG": ("Алжир", "Algeria"),
    "AMD": ("Ахмедабад", "India"),
    "AMM": ("Амман", "Jordan"),
    "AMS": ("Амстердам", "Netherlands"),
    "ASB": ("Ашхабад", "Turkmenistan"),
    "AUH": ("Абу-Даби", "UAE"),
    "AYT": ("Анталья", "Turkey"),
    "BAH": ("Манама", "Bahrain"),
    "BEY": ("Бейрут", "Lebanon"),
    "BGW": ("Багдад", "Iraq"),
    "BHK": ("Бухара", "Uzbekistan"),
    "BKK": ("Бангкок", "Thailand"),
    "BLR": ("Бангалор", "India"),
    "BOM": ("Мумбаи", "India"),
    "BSR": ("Басра", "Iraq"),
    "BSZ": ("Бишкек (Манас)", "Kyrgyzstan"),
    "BUD": ("Будапешт", "Hungary"),
    "CAI": ("Каир", "Egypt"),
    "CAN": ("Гуанчжоу", "China"),
    "CCU": ("Калькутта", "India"),
    "CDG": ("Париж", "France"),
    "CGK": ("Джакарта", "Indonesia"),
    "CGP": ("Читтагонг", "Bangladesh"),
    "CMB": ("Коломбо", "Sri Lanka"),
    "CMN": ("Касабланка", "Morocco"),
    "COK": ("Кочи", "India"),
    "CPT": ("Кейптаун", "South Africa"),
    "CTU": ("Чэнду", "China"),
    "DAC": ("Дакка", "Bangladesh"),
    "DAM": ("Дамаск", "Syria"),
    "DAR": ("Дар-эс-Салам", "Tanzania"),
    "DEL": ("Дели", "India"),
    "DME": ("Москва (Домодедово)", "Russia"),
    "DMM": ("Даммам", "Saudi Arabia"),
    "DOH": ("Доха", "Qatar"),
    "DWC": ("Дубай (Аль-Мактум)", "UAE"),
    "DXB": ("Дубай", "UAE"),
    "DYU": ("Душанбе", "Tajikistan"),
    "EBB": ("Энтеббе", "Uganda"),
    "ERB": ("Эрбиль", "Iraq"),
    "ESB": ("Анкара", "Turkey"),
    "EVN": ("Ереван", "Armenia"),
    "FCO": ("Рим", "Italy"),
    "FEG": ("Фергана", "Uzbekistan"),
    "FJR": ("Фуджейра", "UAE"),
    "FRA": ("Франкфурт", "Germany"),
    "FRU": ("Бишкек", "Kyrgyzstan"),
    "GYD": ("Баку", "Azerbaijan"),
    "HKG": ("Гонконг", "Hong Kong"),
    "HND": ("Токио (Ханеда)", "Japan"),
    "HRG": ("Хургада", "Egypt"),
    "HYD": ("Хайдарабад", "India"),
    "ICN": ("Сеул", "South Korea"),
    "IKT": ("Иркутск", "Russia"),
    "ISB": ("Исламабад", "Pakistan"),
    "IST": ("Стамбул", "Turkey"),
    "JED": ("Джидда", "Saudi Arabia"),
    "JNB": ("Йоханнесбург", "South Africa"),
    "KBL": ("Кабул", "Afghanistan"),
    "KHI": ("Карачи", "Pakistan"),
    "KIV": ("Кишинёв", "Moldova"),
    "KJA": ("Красноярск", "Russia"),
    "KUL": ("Куала-Лумпур", "Malaysia"),
    "KWI": ("Кувейт", "Kuwait"),
    "LED": ("Санкт-Петербург", "Russia"),
    "LHE": ("Лахор", "Pakistan"),
    "LHR": ("Лондон", "UK"),
    "LOS": ("Лагос", "Nigeria"),
    "LWN": ("Гюмри", "Armenia"),
    "MAA": ("Ченнаи", "India"),
    "MBA": ("Момбаса", "Kenya"),
    "MCT": ("Маскат", "Oman"),
    "MED": ("Медина", "Saudi Arabia"),
    "MNL": ("Манила", "Philippines"),
    "MUC": ("Мюнхен", "Germany"),
    "MXP": ("Милан", "Italy"),
    "NBO": ("Найроби", "Kenya"),
    "NMA": ("Наманган", "Uzbekistan"),
    "NRT": ("Токио", "Japan"),
    "NVI": ("Навои", "Uzbekistan"),
    "OSS": ("Ош", "Kyrgyzstan"),
    "OVB": ("Новосибирск", "Russia"),
    "PEK": ("Пекин", "China"),
    "PEW": ("Пешавар", "Pakistan"),
    "PRG": ("Прага", "Czech Republic"),
    "PVG": ("Шанхай", "China"),
    "RIX": ("Рига", "Latvia"),
    "RKT": ("Рас-эль-Хайма", "UAE"),
    "RUH": ("Эр-Рияд", "Saudi Arabia"),
    "SAH": ("Сана", "Yemen"),
    "SAW": ("Стамбул (Сабиха)", "Turkey"),
    "SHJ": ("Шарджа", "UAE"),
    "SIN": ("Сингапур", "Singapore"),
    "SKD": ("Самарканд", "Uzbekistan"),
    "SLL": ("Салала", "Oman"),
    "SSH": ("Шарм-эш-Шейх", "Egypt"),
    "SVO": ("Москва (Шереметьево)", "Russia"),
    "SVX": ("Екатеринбург", "Russia"),
    "TAS": ("Ташкент", "Uzbekistan"),
    "TBS": ("Тбилиси", "Georgia"),
    "TIP": ("Триполи", "Libya"),
    "TLL": ("Таллин", "Estonia"),
    "TSE": ("Астана", "Kazakhstan"),
    "TUN": ("Тунис", "Tunisia"),
    "UGC": ("Ургенч", "Uzbekistan"),
    "URC": ("Урумчи", "China"),
    "VIE": ("Вена", "Austria"),
    "VKO": ("Москва (Внуково)", "Russia"),
    "VNO": ("Вильнюс", "Lithuania"),
    "WAW": ("Варшава", "Poland"),
    "ZRH": ("Цюрих", "Switzerland"),
    "ZYL": ("Силхет", "Bangladesh"),
}

def airport_name(iata):
    """"Дубай (DWC)" when known, otherwise just the code."""
    if not iata or iata in ("—", "", None):
        return "—"
    hit = AIRPORTS.get(iata.upper())
    return f"{hit[0]} ({iata.upper()})" if hit else iata.upper()


def airport_country(iata):
    hit = AIRPORTS.get((iata or "").upper())
    return hit[1] if hit else ""
